name: GitHub Actions Demo
on: [pull_request]
jobs:
  My-First-Github-Job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: hello
        run: |
          echo "Hellow world"
      - name: run python script
        run: |
          pip install -r requirements.txt
          python ci.py

